# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "inferploidy"
version = "0.3.10"
description = "Tookits for Tumor cell identification in single-cell RNA-seq data"
readme = "README.md"
authors = [{ name = "Seokhyun Yoon", email = "syoon@dku.edu" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["single-cell omics", "bioinformatics"]
dependencies = [
    "numpy>=1.26,<2.1",
    "pandas>=2.0,<2.3",
    "matplotlib",
    "gdown",
    "scipy",
    "scikit-learn",
    "anndata>=0.10,<0.12",
    "zarr>=2.18,<3",
    "umap-learn",
    "scanpy>=1.10,<1.12",
    "scikit-network",
    "infercnvpy>=0.6.1",
    "numba>=0.58,<=0.65.1",
]
# requires-python = "<3.11"

[project.optional-dependencies]
dev = ["seaborn"]

[project.urls]
Homepage = "https://github.com/combio-dku"

[project.scripts]
realpython = "reader.__main__:main"
